{% set name = "prettytable" %}
{% set version = "3.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 52f682ba4efe29dccb38ff0fe5bac8a23007d0780ff92a8b85af64bc4fc74d72

build:
  skip: true  # [py<37]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - wheel
    - hatchling
    - hatch-vcs
  run:
    - python
    - importlib-metadata
    - wcwidth
  run_constrained:
    - ptable >=9999

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - prettytable

about:
  home: https://pypi.org/project/prettytable/
  license_file: COPYING
  license: BSD-3-Clause
  license_family: BSD
  summary: Display tabular data in a visually appealing ASCII table format
  description: |
    A simple Python library for easily displaying tabular data in
    a visually appealing ASCII table format
  dev_url: https://github.com/jazzband/prettytable
  doc_url: https://github.com/jazzband/prettytable/blob/master/README.md

extra:
  recipe-maintainers:
    - anguslees
    - licode
    - ericpre
