{% set name = "prettytable" %}
{% set version = "3.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ae7d96c64100543dc61662b40a28f3b03c0f94a503ed121c6fca2782c5816f81

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
  run:
    - python >=3.7
    - importlib-metadata
    - wcwidth
  run_constrained:
    - ptable >=9999

test:
  imports:
    - prettytable

about:
  home: https://github.com/jazzband/prettytable
  license_file: COPYING
  license: BSD-3-Clause
  summary: A simple Python library for easily displaying tabular data in a visually appealing ASCII table format

extra:
  recipe-maintainers:
    - anguslees
    - licode
    - ericpre
