{% set name = "prettytable" %}
{% set version = "3.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3c64b31719d961bf69c9a7e03d0c1e477320906a98da63952bc6698d6164ff57

build:
  skip: true  # [py<39]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - hatchling >=1.27
    - hatch-vcs
  run:
    - python
    - wcwidth
  run_constrained:
    # Following from conda-forge:
    # Prevent ptable from interfering with prettytable
    - ptable >=9999

test:
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -v
  imports:
    - prettytable

about:
  home: https://github.com/prettytable/prettytable
  license_file: COPYING
  license: BSD-3-Clause
  license_family: BSD
  summary: Display tabular data in a visually appealing ASCII table format
  description: |
    A simple Python library for easily displaying tabular data in
    a visually appealing ASCII table format
  dev_url: https://github.com/prettytable/prettytable
  doc_url: https://github.com/prettytable/prettytable

extra:
  recipe-maintainers:
    - anguslees
    - licode
    - ericpre
