{% set name = "prettytable" %}
{% set version = "2.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 18e56447f636b447096977d468849c1e2d3cfa0af8e7b5acfcf83a64790c0aca

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools_scm
  run:
    - python >=3.5
    - importlib-metadata
    - wcwidth
  run_constrained:
    - ptable >=9999

test:
  imports:
    - prettytable

about:
  home: https://github.com/jazzband/prettytable
  license_file: COPYING
  license: BSD-3-Clause
  summary: A simple Python library for easily displaying tabular data in a visually appealing ASCII table format

extra:
  recipe-maintainers:
    - anguslees
    - licode
    - ericpre
