{% set name = "prettytable" %}
{% set version = "3.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3c64b31719d961bf69c9a7e03d0c1e477320906a98da63952bc6698d6164ff57

build:
  skip: true  # [py<39]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - hatch-vcs
    - hatchling >=1.27
  run:
    - python
    - wcwidth
  run_constrained:
    # Following from conda-forge
    # Prevent ptable from interfering with prettytable
    - ptable >=9999

test:
  imports:
    - prettytable
    - prettytable.colortable
    - prettytable.prettytable
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # Cannot invoke upstream tests -> ModuleNotFoundError: No module named 'pytest_lazy_fixtures'
  requires:
    - pip

about:
  home: https://pypi.org/project/prettytable
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: Display tabular data in a visually appealing ASCII table format
  description: |
    A simple Python library for easily displaying tabular data in
    a visually appealing ASCII table format
  dev_url: https://github.com/jazzband/prettytable
  doc_url: https://github.com/jazzband/prettytable/blob/master/README.md

extra:
  recipe-maintainers:
    - anguslees
    - licode
    - ericpre