travis:
  secure:
    BINSTAR_TOKEN: CHSIHZJxZc23mT88hppKsZ7rknLXEICvK0T7cGWmFCpQn+LElpyEXIjaMJmvomL01GhLRhmucyQPv5dn/udtwhBahSOtlsUs47JJohWPGeSeBOlEAqN+hzsosGB08rB5CTsZhptw6K5MiTeFAaoy4+7BgW6yTWdE1GsH72PQgiZteD4Fmqfo9Wz9K/X8oU48chaGPSpNJav+zkXQ1KGDMKIA0+I0Au8HBrUiTrOAjrg2vzJrMKYEMQ0Y8EJMxiAmXwWAylmtoUz8mZNG1jIV7OfTZ5wjR8tcZD5KjSSuYIOyUX8A8QVbyyAizQzmJlkxqdO1V67lgZqWzEcbs5L0Ywi1SwR5CU86ZNob2G3zTPgYe6PFHAcZLD8nilgUmnEbVAEM9N/bm8tYqNYczIGMH+stIyKumjRRUSBZyyJRQhrA688yW573w6MuBhJH6q/S1CPlf4peWhVwmjhSwKofNzsfsFwkCA8YEKIljlEhPhSlmrQCANgi8Tg3ZIos8RwCQlhra2DAEH78eK62z24RdbdcnsRA8xfymlBqFVFtDdm0uV6BTTUbyHd12Ne8VtwQOeWVKF5e6v1yNtq28fEU2PChwDlXco8/mv59Y4QNl6NpiaBiw9MztS1mhLB3oMpbp6M6cG3NA4fGxfR0jjYeZm90vVcQKP5I8zV/hMbE5UI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
