travis:
  secure:
    BINSTAR_TOKEN: S0yPoRTJlltPv6vUJQwkVNGFsB+SHwFeAtKIxdMmXJbfxfZQmRKEk23u5HD3MVeiVpLd2i1b3qgFYSexxgyJNmWqzltvY3g50USTgNMbTE1nY5HuqZRL2Uj6fU4lDZXFE16jl5HPJ67BepQae2xjN5qr5LQMWJMxyYHzQWnHzKK2suZAqEhjQQwCQHflMyrZe1J1PS76h3jeF7IKJe7FMfn6wPOl+W3BzQPUrWXVN7Up8V/EN/ClD+0XZEHDYvclEeeUxfBsqQBUH9KrpIknNSfI3pdz2eiaDpNq/4VxTmVWkqHB885+80BfdlY/OxC/m+JuMrUghpoWEu/28BzIhfCQlyxKGgTmb1Hj82CJVK8t6EJEpnQW4rsjej/eRvV/I47zSKc29Jhi1nh2VMlVzaAJm/cbQBT5o+K1y7JOQU0aTgGH5pM5/T0uTd4ZVX5vwg4JpNNoz28fcfvWZ8NFBPup8HEKzlI7SAB4476n3n/ubmxo1zEQxog36B+SGNP7c6rhzBl7fnH+zczvLODZGrzssmPFneRjkSRlFQgVXbyiiXRWknOBJTiuP0+XaNc8Wm+aQV04y/xIYqBiBae9syNiKArs2zqKfIOQ8dab+T3Rn/BEYRG1LCdoj5B1/lkj5NRe7ekpIqG6YEpuP+x4Inl33dhUVjYswj1IAs5iPt0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
