travis:
  secure:
    BINSTAR_TOKEN: kmcJrzxj464rdGC2JTfyPGdR+N005nZZIxzPv7iILvEbbDsU9L1o3JiGbHWvmekdnbmaFXiaPlw/CYwmhk0hJhd3lnXXrHhvhYY11KEA6VytZoSkqfE0CrK5lyl34IkWFKQRXsNWcTS7P+FrGZOVYlSYVoE1E+umsMKrDBs0iUvv0TK/+WaG5SVIOLVq+rOqbdgeiu56yaOnbExca0GHg9xIs77nEFMEs7lH/U/zuxubB1UU9KpwDsK7pjPq3+qi1Cjlb2FBDGZzqv4B/jzJR4rHj72PyyriFoA+FGIhvXq6b4W29umHUc5flxoDbNVPolWJ0F1ykR96EoKp2eEjNEYoNHUxC5aM40OHiJ+zVQoi+fDr6Wq0znfq+Yay0IZVpzNwHzJgHVvjaXvqsQhMzPcvtB7UioMOiGTWmj+ufCaRIcEDJA4vEiJmgRN2wmCV0dE+hHLGqg2jAmMNan/MmVfrWWEy2GFl686fX0HUOMc+ydCmX4afNYzRJ6aC/n6m/kBhRXqyGnap6kgaYhLnN8GmZUjAEEAH2snEk73kQA+O/sGRECZY1eo8noFv8F1n0NTIA/P3zok9SV+rd2b4/hz1E1dn5EQAjI6abzw+LTOnjGsK1H5LwF+Pf7h48dHiErlP7U94e3Vew2C5KEagobh8V+5bvlnMEx+vO5Yonag=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
